smoking updated; trello cleanup
nyaayaIN/webapp pull request #16
Opened 2018-02-27 10:43 UTC by saurabhariyan

- content changes only.

2018-02-27 19:42 UTC, archanks approved these changes

2018-02-27 19:43 UTC, archanks requested changes

2018-02-27 19:43 UTC, archanks commented on src/data/topic_mock.json
> +        "id": "glos05",
don't use the same id

2018-02-27 19:43 UTC, archanks commented on src/data/topic_mock.json
> +        "id": "glos05",
update id properly

2018-02-28 05:21 UTC, saurabhariyan commented on src/data/topic_mock.json
> +        "id": "glos05",
resolved.

2018-04-06 21:49 UTC, closed without merging